# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='user',
        ),
        migrations.AddField(
            model_name='venue',
            name='map_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='program',
            name='speakers',
        ),
        migrations.AddField(
            model_name='program',
            name='speakers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
