# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Venue')),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='speakers',
            field=models.ManyToManyField(to='meetup.Speaker'),
        ),
        migrations.AddField(
            model_name='program',
            name='meet_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetup.MeetUp'),
        ),
    ]
