# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20171102_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='program',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_main_event',
            field=models.BooleanField(default=True, verbose_name='If kind of session or lecture True, or not False'),
        ),
    ]
