# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='imp_uid',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='merchant_uid',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_close_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Registration'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='meet_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.MeetUp'),
        ),
    ]
